# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test app"
client_id = "2ac9049cf928bec5946372766744ef70"
application_url = "https://bookmarks-memphis-revolutionary-even.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://bookmarks-memphis-revolutionary-even.trycloudflare.com/auth/shopify/callback",
  "https://bookmarks-memphis-revolutionary-even.trycloudflare.com/authSa/shopify/callback",
  "https://bookmarks-memphis-revolutionary-even.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avada-training-app.myshopify.com"
